server:
  port: 8083
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  ai:
    minimax:
      api-key: sk-cp-NtJsjzVVVBlIGqKmL2mwoeqraEWmJiCOvw3i7v80cJ479hYg6rXhBvSqmi5p1lmKkL-XcHp15sSVugNXhmFVjH_Q4BjUQ-cV5n-Nkh6aGgC0n452DM3q5yg
      base-url: https://api.minimaxi.com
      chat:
        options:
          model: MiniMax-M2.5-highspeed
  http:
    encoding:
      charset: UTF-8
      enabled: true
rag:
  service:
    base-url: http://localhost:8082
