server:
  port: 8080
logging:
  level:
    root: info
  charset:
    console: UTF-8
    file: UTF-8
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } --- [%t] %-40.40logger{39} : %m%n"
spring:
  mvc:
    async:
      request-timeout: 300000 # 全局异步超时时间，单位：毫秒，5分钟
      # request-timeout: 0  # 永不超时
  datasource:
    url: jdbc:mysql://localhost:3306/invoicedb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  ai:
    minimax: # 关键：必须是openai节点，siliconflow兼容openai协议
      api-key: sk-cp-NtJsjzVVVBlIGqKmL2mwoeqraEWmJiCOvw3i7v80cJ479hYg6rXhBvSqmi5p1lmKkL-XcHp15sSVugNXhmFVjH_Q4BjUQ-cV5n-Nkh6aGgC0n452DM3q5yg
      base-url: https://api.minimaxi.com
      chat:
        options:
          model: MiniMax-M2.5-highspeed # 指定调用的大模型
    openai:  # 关键：必须是openai节点，siliconflow兼容openai协议
      api-key: sk-sgtdkfkgpctkajpgngyeqmuukjetgbgjvlznrhmtwuazmaij
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: deepseek-ai/DeepSeek-V3.2 # 指定调用的大模型
      embedding:
        options:
          model: Qwen/Qwen3-Embedding-8B

#    mcp:
#      client:
#        streamable-http:
#          connections:
#                server2:
#                  url: http://127.0.0.1:8081
        #        sse:
#          connections:

#            server2:
#              url: http://127.0.0.1:8081
#              sse-endpoint: /sse




            
